[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "product-review-api"

[services.variables]
SPRING_PROFILES_ACTIVE = "prod"
PORT = "8080"
